"""empty message

Revision ID: 545eaf72f371
Revises: 7f52f902fcc8
Create Date: 2023-03-19 16:05:14.204469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545eaf72f371'
down_revision = '7f52f902fcc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
